### PR TITLE
linux/arm64 support

### PR DESCRIPTION
**Pull request by phosae**
use Docker Buildx for multi arch support

### CODE REVIEW

**Comment by phosae** [comment]
@slok

**Comment by phosae** [comment]
would you like to build/push in one command? the build command can be improved by add `--push`

```
docker buildx build --platform linux/amd64,linux/arm64 -t $(IMAGE) --push .
```

**Comment by slok** [comment]
All the build system changed on CI and also for now we don't need to support multiarch, most people seem to be ok with amd64, if this changes in the future we can rethink about how to do it. Closing.

Many thanks!

**Comment by nantiferov** [comment]
I'm not sure if it's better to open a new issue, but considering inevitable growth of ARM64 in both workstations and servers, would be great to have multi-arch (amd64/arm64) docker image for this project.

I can create PR with updated CI if you don't mind.

**Pull request closed without merging**
